#!/bin/bash -e
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

if [[ $(echo ${user_data_trace_log}) == false ]]; then
  set -x
fi

# Add current hostname to hosts file
tee /etc/hosts <<EOL
127.0.0.1   localhost localhost.localdomain $(hostname)
EOL

${eip}

for i in {1..7}; do
  echo "Attempt: ---- " $i
  yum -y update && break || sleep 60
done

echo "#!/bin/bash" >> /home/ec2-user/userdata.sh

echo "cat /etc/resolv.conf" >> /home/ec2-user/userdata.sh
echo "ping eu-west-2.compute.internal" >> /home/ec2-user/userdata.sh
echo "echo \"options timeout:2 attempts:5\" >> /etc/resolv.conf" >> /home/ec2-user/userdata.sh
echo "echo \"; generated by /home/ec2-user/userdata.sh\" >> /etc/resolv.conf" >> /home/ec2-user/userdata.sh
echo "echo \"eu-west-2.compute.internal\" >> /etc/resolv.conf" >> /home/ec2-user/userdata.sh
echo "echo \"nameserver 172.31.0.2\" >> /etc/resolv.conf" >> /home/ec2-user/userdata.sh
echo "cat /etc/resolv.conf" >> /home/ec2-user/userdata.sh

echo "mkdir /efs" >> /home/ec2-user/userdata.sh
#echo "apt-get update" >> /home/ec2-user/userdata.sh
#echo "apt-get -y install git binutils" >> /home/ec2-user/userdata.sh
#echo "git clone https://github.com/aws/efs-utils" >> /home/ec2-user/userdata.sh
#echo "cd efs-utils" >> /home/ec2-user/userdata.sh
#echo "./build-deb.sh" >> /home/ec2-user/userdata.sh
#echo "sudo apt-get -y install ./build/amazon-efs-utils*deb" >> /home/ec2-user/userdata.sh
echo "mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 10.0.1.4:/ /efs" >> /home/ec2-user/userdata.sh


${logging}

${gitlab_runner}
